### ISSUE TITLE
No instrumentation runner found on device emulator-12622 for package *

### ISSUE THREAD

**Issue by xiongemi** [expo/config-plugins#173]
### Summary

when runing android detox e2e tests with @config-plugins/detox, failed with this error: `No instrumentation runner found on device emulator-12622 for package *`.
detox testing works fine for ios.

### Config Plugin

@config-plugins/detox

### What platform(s) does this occur on?

Android

### SDK Version

48.0.15

### Reproducible demo

-use detox 48.0.15
- add "@config-plugins/detox": "^5.0.1"
- add @config-plugins/detox to plugins in app.json
- build android app
- try e2e test with android
got this error:
```
14:11:39.423 detox[18657] i app.spec.ts is assigned to emulator-12622 (Pixel_XL_API_Tiramisu)
14:11:39.676 detox[18657] i Cats: should display carousel
14:11:39.678 detox[18657] i Cats: should display carousel [FAIL]

 FAIL  src/app.spec.ts
  Cats
    ✕ should display carousel (2 ms)

  ● Cats › should display carousel

    No instrumentation runner found on device emulator-12622 for package com.exiong.cats

      4 |   await device.launchApp();
      5 | });
    > 6 |
        | ^

      at test-setup.ts:6:26
      at ../../node_modules/tslib/tslib.js:167:75
      at Object.__awaiter (../../node_modules/tslib/tslib.js:163:16)
      at Object.<anonymous> (test-setup.ts:5:25)
```

**Comment by hassankhan** [comment]
Closing as `@config-plugins/detox` is no longer maintained.
